apiVersion: v1
kind: Template
metadata:
  name: advisor-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: advisor
    spec:
      envName: ${ENV_NAME}
      title: Advisor
      deploymentRepo: https://github.com/RedHatInsights/insights-advisor-frontend
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/advisor
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: "/apps/advisor/fed-mods.json"
        modules:
          - id: "advisor"
            module: "./RootApp"
            routes:
              - pathname: /insights/advisor
              - pathname: /ansible/advisor

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/insights-management-tenant/insights-advisor/advisor-frontend
